package com.path.core.entity;

// Generated 2015-12-21 10:56:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TbPath generated by hbm2java
 */
@Entity
@Table(name = "tb_path", catalog = "path")
public class TbPath implements java.io.Serializable {

	private long pathid;
	private String name;
	private Integer volume;
	private Integer leftnum;
	private String sex;
	private Set<TbLog> tbLogs = new HashSet<TbLog>(0);

	public TbPath() {
	}

	public TbPath(long pathid) {
		this.pathid = pathid;
	}

	public TbPath(long pathid, String name, Integer volume, Integer leftnum,
			String sex, Set<TbLog> tbLogs) {
		this.pathid = pathid;
		this.name = name;
		this.volume = volume;
		this.leftnum = leftnum;
		this.sex = sex;
		this.tbLogs = tbLogs;
	}

	@Id
	@Column(name = "pathid", unique = true, nullable = false)
	@GeneratedValue(generator = "pathtableGenerator")
	@GenericGenerator(name = "pathtableGenerator", strategy = "increment")
	public long getPathid() {
		return this.pathid;
	}

	public void setPathid(long pathid) {
		this.pathid = pathid;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "volume")
	public Integer getVolume() {
		return this.volume;
	}

	public void setVolume(Integer volume) {
		this.volume = volume;
	}

	@Column(name = "leftnum")
	public Integer getLeftnum() {
		return this.leftnum;
	}

	public void setLeftnum(Integer leftnum) {
		this.leftnum = leftnum;
	}

	@Column(name = "sex", length = 20)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbPath")
	public Set<TbLog> getTbLogs() {
		return this.tbLogs;
	}

	public void setTbLogs(Set<TbLog> tbLogs) {
		this.tbLogs = tbLogs;
	}

}
